export const cartas = [
    { nombre: "El Loco", archivo: "el-loco.jpg" },
    { nombre: "El Mago", archivo: "el-mago.jpg" },
    { nombre: "El Sumosacerdote", archivo: "el-sumosacerdote.jpg" },
    { nombre: "La Luna", archivo: "la-luna.jpg" },
    { nombre: "El Sol", archivo: "el-sol.jpg" },
    { nombre: "La Muerte", archivo: "la-muerte.jpg" },
    { nombre: "El Mundo", archivo: "el-mundo.jpg" },
    { nombre: "El Carro", archivo: "el-carro.jpg" },
    { nombre: "El Ermitaño", archivo: "el-ermitaño.jpg" },
    { nombre: "La Sacerdotisa", archivo: "la-sacerdotisa.jpg" },
    { nombre: "La Estrella", archivo: "la-estrella.jpg" },
    { nombre: "La Torre", archivo: "la-torre.jpg" },
    { nombre: "La Emperatriz", archivo: "la-emperatriz.jpg" },
    { nombre: "La Rueda", archivo: "la-rueda.jpg" },
    { nombre: "La Templanza", archivo: "la-templanza.jpg" },
    { nombre: "La Justicia", archivo: "la-justicia.jpg" },
    { nombre: "Los Amantes", archivo: "los-amantes.jpg" },
    { nombre: "El Emperador", archivo: "el-emperador.jpg" },
    { nombre: "La Fuerza", archivo: "la-fuerza.jpg" },
    { nombre: "El Colgado", archivo: "el-colgado.jpg" },
    { nombre: "El Diablo", archivo: "el-diablo.jpg" },
    { nombre: "El Juicio", archivo: "el-juicio.jpg" }
];
